name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup pnpm
      uses: pnpm/action-setup@v1.2.1
      with:
        version: ^5.5.4
    - name: Install
      run: pnpm install --frozen-lockfile=false
    - name: Build
      run: pnpm run build
    - name: Lint
      run: pnpm run lint
    - name: Run unit tests
      run: pnpm test
    - name: Build documentation
      run: pnpm run docs
    - name: Upload code coverage to codecov
      uses: codecov/codecov-action@v1
